insert or ignore into categories (name, slug, sort_order, active)
values
  ('Le Pizze', 'le-pizze', 10, 1),
  ('Le Bianche', 'le-bianche', 20, 1),
  ('Le Speciali', 'le-speciali', 30, 1),
  ('I Calzoni', 'i-calzoni', 40, 1),
  ('Calzoni in Fritteria', 'calzoni-in-fritteria', 50, 1);

insert or ignore into ingredients (name, slug, allergen_info, active)
values
  ('''Nduja', 'nduja', null, 1),
  ('Acciughe', 'acciughe', 'pesce', 1),
  ('Anelli di porro', 'anelli-di-porro', null, 1),
  ('Basilico', 'basilico', null, 1),
  ('Brie', 'brie', 'latte e derivati', 1),
  ('Bufala Campana DOP', 'bufala-campana-dop', 'latte e derivati', 1),
  ('Bufala campana DOP bio', 'bufala-campana-dop-bio', 'latte e derivati', 1),
  ('Burrata', 'burrata', 'latte e derivati', 1),
  ('Caciocavallo della Piana', 'caciocavallo-della-piana', 'latte e derivati', 1),
  ('Capperi', 'capperi', null, 1),
  ('Carciofi', 'carciofi', null, 1),
  ('Carciofo alla griglia', 'carciofo-alla-griglia', null, 1),
  ('Cipolla', 'cipolla', null, 1),
  ('Cipolla caramellata', 'cipolla-caramellata', null, 1),
  ('Coppa affinata in Amarone DOCG', 'coppa-affinata-in-amarone-docg', null, 1),
  ('Cozze e frutti di mare', 'cozze-e-frutti-di-mare', 'molluschi', 1),
  ('Crema al pistacchio', 'crema-al-pistacchio', 'frutta a guscio, latte e derivati', 1),
  ('Crema carbonara', 'crema-carbonara', 'latte e derivati, uova e derivati', 1),
  ('Crudo di Parma DOP 24/30 mesi', 'crudo-di-parma-dop-24-30-mesi', null, 1),
  ('Doppia salsa di pomodoro', 'doppia-salsa-di-pomodoro', null, 1),
  ('Emmenthal', 'emmenthal', 'latte e derivati', 1),
  ('Fili di peperoncino', 'fili-di-peperoncino', null, 1),
  ('Friarielli passati in padella con aglio', 'friarielli-passati-in-padella-con-aglio', null, 1),
  ('Funghi', 'funghi', null, 1),
  ('Funghi freschi', 'funghi-freschi', null, 1),
  ('Gamberetti', 'gamberetti', 'crostacei', 1),
  ('Gelatina di Amarone DOCG', 'gelatina-di-amarone-docg', null, 1),
  ('Gorgonzola', 'gorgonzola', 'latte e derivati', 1),
  ('Grana', 'grana', 'latte e derivati', 1),
  ('Guanciale affumicato', 'guanciale-affumicato', null, 1),
  ('Lombo stagionato al pepe rosa', 'lombo-stagionato-al-pepe-rosa', null, 1),
  ('Melanzane grigliate', 'melanzane-grigliate', null, 1),
  ('Misto bosco', 'misto-bosco', null, 1),
  ('Monte Veronese DOP', 'monte-veronese-dop', 'latte e derivati', 1),
  ('Mortadella Bologna DOP', 'mortadella-bologna-dop', null, 1),
  ('Mozzarella', 'mozzarella', 'latte e derivati', 1),
  ('Noci', 'noci', 'frutta a guscio', 1),
  ('Olio all''aglio', 'olio-allaglio', null, 1),
  ('Olio extravergine', 'olio-extravergine', null, 1),
  ('Olio extravergine Chianti DOP', 'olio-extravergine-chianti-dop', null, 1),
  ('Olive nere', 'olive-nere', null, 1),
  ('Origano', 'origano', null, 1),
  ('Origano siciliano', 'origano-siciliano', null, 1),
  ('Pancetta affumicata', 'pancetta-affumicata', null, 1),
  ('Pancetta arrotolata piccante', 'pancetta-arrotolata-piccante', null, 1),
  ('Patate cubettate al forno', 'patate-cubettate-al-forno', null, 1),
  ('Patatine fritte', 'patatine-fritte', null, 1),
  ('Pecorino Reggino', 'pecorino-reggino', 'latte e derivati', 1),
  ('Pepe', 'pepe', null, 1),
  ('Peperoncini in fili sottili', 'peperoncini-in-fili-sottili', null, 1),
  ('Peperoncino', 'peperoncino', null, 1),
  ('Peperoni grigliati', 'peperoni-grigliati', null, 1),
  ('Pesto homemade', 'pesto-homemade', null, 1),
  ('Philadelphia', 'philadelphia', 'latte e derivati', 1),
  ('Pinoli', 'pinoli', null, 1),
  ('Pomodorini cirio', 'pomodorini-cirio', null, 1),
  ('Pomodorini freschi', 'pomodorini-freschi', null, 1),
  ('Pomodorini secchi', 'pomodorini-secchi', null, 1),
  ('Pomodorino confit', 'pomodorino-confit', null, 1),
  ('Pomodoro', 'pomodoro', null, 1),
  ('Porcini', 'porcini', null, 1),
  ('Prezzemolo', 'prezzemolo', null, 1),
  ('Prosciutto', 'prosciutto', null, 1),
  ('Radicchio', 'radicchio', null, 1),
  ('Ricotta', 'ricotta', 'latte e derivati', 1),
  ('Rosmarino', 'rosmarino', null, 1),
  ('Rucola', 'rucola', null, 1),
  ('Salamino piccante', 'salamino-piccante', null, 1),
  ('Scaglie di grana', 'scaglie-di-grana', 'latte e derivati', 1),
  ('Scamorza affumicata', 'scamorza-affumicata', 'latte e derivati', 1),
  ('Schiacciata', 'schiacciata', null, 1),
  ('Soppressa dolce della Lessinia', 'soppressa-dolce-della-lessinia', null, 1),
  ('Speck Alto Adige IGP', 'speck-alto-adige-igp', null, 1),
  ('Spinaci', 'spinaci', null, 1),
  ('Straccetti di melanzana fritta', 'straccetti-di-melanzana-fritta', null, 1),
  ('Stracchino', 'stracchino', 'latte e derivati', 1),
  ('Stracciatella', 'stracciatella', 'latte e derivati', 1),
  ('Tastasal', 'tastasal', null, 1),
  ('Tentacoli di polpo', 'tentacoli-di-polpo', 'molluschi', 1),
  ('Tonno', 'tonno', 'pesce', 1),
  ('Verdure di stagione', 'verdure-di-stagione', null, 1),
  ('Wurstel', 'wurstel', null, 1),
  ('Zucchine grigliate', 'zucchine-grigliate', null, 1);

insert or ignore into extra_ingredients (ingredient_id, extra_price, active, sort_order)
values
  ((select id from ingredients where slug = 'mozzarella'), 1.50, 1, 10),
  ((select id from ingredients where slug = 'bufala-campana-dop'), 3.00, 1, 20),
  ((select id from ingredients where slug = 'burrata'), 3.50, 1, 30),
  ((select id from ingredients where slug = 'stracciatella'), 3.00, 1, 40),
  ((select id from ingredients where slug = 'gorgonzola'), 2.00, 1, 50),
  ((select id from ingredients where slug = 'nduja'), 2.50, 1, 60),
  ((select id from ingredients where slug = 'salamino-piccante'), 2.50, 1, 70),
  ((select id from ingredients where slug = 'olive-nere'), 1.20, 1, 80),
  ((select id from ingredients where slug = 'funghi-freschi'), 2.00, 1, 90),
  ((select id from ingredients where slug = 'porcini'), 2.50, 1, 100),
  ((select id from ingredients where slug = 'prosciutto'), 2.20, 1, 110),
  ((select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 3.50, 1, 120),
  ((select id from ingredients where slug = 'scamorza-affumicata'), 2.20, 1, 130),
  ((select id from ingredients where slug = 'grana'), 1.50, 1, 140),
  ((select id from ingredients where slug = 'peperoni-grigliati'), 1.80, 1, 150),
  ((select id from ingredients where slug = 'cipolla'), 1.00, 1, 160),
  ((select id from ingredients where slug = 'tonno'), 2.80, 1, 170),
  ((select id from ingredients where slug = 'patate-cubettate-al-forno'), 1.80, 1, 180),
  ((select id from ingredients where slug = 'philadelphia'), 2.20, 1, 190),
  ((select id from ingredients where slug = 'basilico'), 0.80, 1, 200);

insert or ignore into menu_items (
  category_id,
  name,
  slug,
  description,
  base_price,
  image_url,
  tags,
  active,
  featured,
  sort_order
)
values
  (
    (select id from categories where slug = 'le-pizze'),
    'Ale',
    'ale',
    'pomodoro, mozzarella, funghi freschi, tastasal, monte veronese dop',
    9.90,
    null,
    '[]',
    1,
    0,
    10
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Andrè',
    'andre',
    'pomodoro, peperoni grigliati, gorgonzola, ''nduja',
    9.10,
    null,
    '[]',
    1,
    0,
    20
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Baldo',
    'baldo',
    'pomodoro, mozzarella, patate cubettate al forno, porcini, wurstel, scamorza affumicata',
    9.40,
    null,
    '[]',
    1,
    0,
    30
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Boscalola',
    'boscalola',
    'pomodoro, mozzarella, porcini, grana, salamino piccante',
    9.20,
    null,
    '["piccante"]',
    1,
    0,
    40
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Briosa',
    'briosa',
    'pomodoro, mozzarella, pancetta affumicata, grana, patate cubettate al forno, brie',
    10.00,
    null,
    '[]',
    1,
    0,
    50
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Bufalina',
    'bufalina',
    'pomodoro, bufala campana dop, pomodorini freschi, olive nere, basilico, olio extravergine (tutto fuori cottura)',
    9.40,
    null,
    '[]',
    1,
    1,
    60
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Calabrese',
    'calabrese',
    'pomodoro, mozzarella, olive nere, pecorino reggino, ''nduja',
    9.10,
    null,
    '["piccante"]',
    1,
    0,
    70
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Campagnola',
    'campagnola',
    'pomodoro, mozzarella, prosciutto, pomodorini cirio, olive nere, scaglie di grana',
    9.20,
    null,
    '[]',
    1,
    0,
    80
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Capricciosa',
    'capricciosa',
    'pomodoro, mozzarella, prosciutto, funghi, carciofi, olive nere, capperi, acciughe, origano siciliano',
    9.50,
    null,
    '[]',
    1,
    0,
    90
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Caretera',
    'caretera',
    'pomodoro, mozzarella, radicchio, gorgonzola, tastasal, speck alto adige igp',
    9.40,
    null,
    '[]',
    1,
    0,
    100
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Deliziosa',
    'deliziosa',
    'pomodoro, mozzarella, zucchine grigliate, pomodorini cirio, philadelphia',
    9.30,
    null,
    '[]',
    1,
    0,
    110
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Estate',
    'estate',
    'pomodoro, mozzarella, pomodorini cirio, scaglie di grana, basilico (tutto fuori cottura)',
    8.70,
    null,
    '[]',
    1,
    0,
    120
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Filanda',
    'filanda',
    'pomodoro, mozzarella, radicchio, philadelphia, scaglie di grana',
    9.20,
    null,
    '[]',
    1,
    0,
    130
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Golosa',
    'golosa',
    'pomodoro, mozzarella, porcini, crudo di parma dop 24/30 mesi, gorgonzola',
    9.40,
    null,
    '[]',
    1,
    0,
    140
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Incontri',
    'incontri',
    'pomodoro, mozzarella, crudo di parma dop 24/30 mesi, stracciatella, pesto homemade',
    10.20,
    null,
    '[]',
    1,
    1,
    150
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Inferno',
    'inferno',
    'pomodoro, mozzarella, ''nduja, salamino piccante, peperoncino',
    9.40,
    null,
    '["piccante"]',
    1,
    0,
    160
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Margherita',
    'margherita',
    'pomodoro, mozzarella',
    6.45,
    null,
    '[]',
    1,
    0,
    170
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Margherita 2.0',
    'margherita-2-0',
    'pomodoro, bufala campana dop bio, pomodorino confit, basilico (tutto in cottura)',
    10.00,
    null,
    '["vegetariana"]',
    1,
    0,
    180
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Marinara',
    'marinara',
    'pomodoro, olio all''aglio, origano siciliano',
    5.85,
    null,
    '[]',
    1,
    0,
    190
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Paradiso',
    'paradiso',
    'pomodoro, mozzarella, funghi freschi, ricotta, crudo di parma dop 24/30 mesi',
    10.20,
    null,
    '[]',
    1,
    0,
    200
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Partenopea',
    'partenopea',
    'pomodoro, mozzarella, pomodorini secchi, tonno, bufala campana dop, cipolla, basilico',
    10.60,
    null,
    '[]',
    1,
    0,
    210
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Parmigiana Crunch',
    'parmigiana-crunch',
    'pomodoro, mozzarella, straccetti di melanzana fritta, grana',
    9.40,
    null,
    '[]',
    1,
    0,
    220
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Patatine Fritte',
    'patatine-fritte',
    'pomodoro, mozzarella, patatine fritte',
    8.20,
    null,
    '[]',
    1,
    0,
    230
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Pizza della Casa',
    'pizza-della-casa',
    'pomodoro, mozzarella, salamino piccante, olive nere, prosciutto, funghi, peperoni grigliati, wurstel',
    10.40,
    null,
    '["piccante"]',
    1,
    0,
    240
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Pizza Scegli Tu',
    'pizza-scegli-tu',
    'pomodoro, mozzarella, 4 gusti a piacere. Indica la combinazione desiderata nelle note ordine.',
    11.30,
    null,
    '["personalizzabile"]',
    1,
    0,
    250
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Prosciutto e Funghi',
    'prosciutto-e-funghi',
    'pomodoro, mozzarella, funghi, prosciutto',
    8.90,
    null,
    '[]',
    1,
    0,
    260
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Pugliese',
    'pugliese',
    'pomodoro, salamino piccante, olive nere, scamorza affumicata',
    8.60,
    null,
    '["piccante"]',
    1,
    0,
    270
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    '4 Formaggi',
    '4-formaggi',
    'pomodoro, mozzarella, scamorza affumicata, emmenthal, ricotta, gorgonzola',
    9.10,
    null,
    '[]',
    1,
    0,
    280
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    '4 Stagioni',
    '4-stagioni',
    'pomodoro, mozzarella, prosciutto, funghi, carciofi, olive nere',
    9.00,
    null,
    '[]',
    1,
    0,
    290
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Rione',
    'rione',
    'pomodoro, mozzarella, funghi, scamorza affumicata, grana, speck alto adige igp',
    9.30,
    null,
    '[]',
    1,
    0,
    300
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Romanaccia',
    'romanaccia',
    'pomodoro, mozzarella, guanciale affumicato, crema carbonara',
    12.00,
    null,
    '[]',
    1,
    0,
    310
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Rustichella',
    'rustichella',
    'pomodoro, mozzarella, stracchino, porcini, grana, speck alto adige igp',
    9.60,
    null,
    '[]',
    1,
    0,
    320
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Sotto Bosco',
    'sotto-bosco',
    'pomodoro, mozzarella, cipolla caramellata, misto bosco, soppressa dolce della lessinia',
    11.00,
    null,
    '[]',
    1,
    0,
    330
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Sfiziosa',
    'sfiziosa',
    'pomodoro, melanzane grigliate, bufala campana dop, olive nere, pomodorini cirio (fuori cottura)',
    10.40,
    null,
    '[]',
    1,
    0,
    340
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Siciliana',
    'siciliana',
    'pomodoro, salamino piccante, olive nere, acciughe, capperi, origano siciliano',
    8.50,
    null,
    '["piccante"]',
    1,
    0,
    350
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Tonno e Cipolla',
    'tonno-e-cipolla',
    'pomodoro, mozzarella, tonno, cipolla',
    8.70,
    null,
    '[]',
    1,
    0,
    360
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Vegetariana',
    'vegetariana',
    'pomodoro, mozzarella, verdure di stagione',
    9.10,
    null,
    '["vegetariana"]',
    1,
    0,
    370
  ),
  (
    (select id from categories where slug = 'le-pizze'),
    'Vulcano',
    'vulcano',
    'pomodoro, guanciale affumicato, patate cubettate al forno, friarielli passati in padella con aglio, burrata, fili di peperoncino (burrata e peperoncino fuori cottura)',
    13.20,
    null,
    '["piccante"]',
    1,
    1,
    380
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Matteo',
    'matteo',
    'mozzarella, gorgonzola, crudo di parma dop 24/30 mesi, rucola, funghi freschi, noci',
    10.60,
    null,
    '["bianca"]',
    1,
    0,
    390
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Mik',
    'mik',
    'mozzarella, spinaci, ricotta, salamino piccante, carciofi',
    9.30,
    null,
    '["bianca","piccante"]',
    1,
    0,
    400
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Peperina',
    'peperina',
    'mozzarella, zucchine grigliate, pancetta arrotolata piccante, stracciatella, peperoncini in fili sottili',
    10.90,
    null,
    '["bianca","piccante"]',
    1,
    0,
    410
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Sapore d''Amarone',
    'sapore-d-amarone',
    'mozzarella, gelatina di amarone docg, coppa affinata in amarone docg, radicchio, anelli di porro',
    12.20,
    null,
    '["bianca"]',
    1,
    0,
    420
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Stanca Bianca',
    'stanca-bianca',
    'mozzarella, stracchino, crudo di parma dop 24/30 mesi, porcini',
    9.40,
    null,
    '["bianca"]',
    1,
    0,
    430
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Trionfo',
    'trionfo',
    'mozzarella, funghi freschi, pomodorini cirio, rucola, burrata',
    11.40,
    null,
    '["bianca"]',
    1,
    0,
    440
  ),
  (
    (select id from categories where slug = 'le-bianche'),
    'Tatanka',
    'tatanka',
    'mozzarella, patate cubettate al forno, brie, rosmarino, crudo di parma dop 24/30 mesi',
    9.40,
    null,
    '["bianca"]',
    1,
    0,
    450
  ),
  (
    (select id from categories where slug = 'le-speciali'),
    'Amatriciana',
    'amatriciana',
    'pomodoro, pancetta affumicata, misto bosco, pepe, caciocavallo della piana',
    11.00,
    null,
    '["speciale"]',
    1,
    0,
    460
  ),
  (
    (select id from categories where slug = 'le-speciali'),
    'Polpo Intanato',
    'polpo-intanato',
    'doppia salsa di pomodoro, tentacoli di polpo, olive nere, basilico (pizza ripiena)',
    15.00,
    null,
    '["speciale"]',
    1,
    0,
    470
  ),
  (
    (select id from categories where slug = 'le-speciali'),
    'Frutti di Mare',
    'frutti-di-mare',
    'pomodoro, mozzarella, cozze e frutti di mare, prezzemolo',
    11.80,
    null,
    '["speciale"]',
    1,
    0,
    480
  ),
  (
    (select id from categories where slug = 'le-speciali'),
    'New York Ale',
    'new-york-ale',
    'pomodoro, mozzarella, burrata, mortadella bologna dop, crema al pistacchio, pomodorini freschi',
    12.70,
    null,
    '["speciale"]',
    1,
    1,
    490
  ),
  (
    (select id from categories where slug = 'le-speciali'),
    'Madame',
    'madame',
    'pomodoro, mozzarella, gamberetti, zucchine grigliate, philadelphia, pinoli, burrata, basilico',
    11.80,
    null,
    '["speciale"]',
    1,
    0,
    500
  ),
  (
    (select id from categories where slug = 'le-speciali'),
    'Toscanaccia',
    'toscanaccia',
    'schiacciata, lombo stagionato al pepe rosa, grana, carciofo alla griglia, olio extravergine chianti dop',
    11.70,
    null,
    '["speciale"]',
    1,
    0,
    510
  ),
  (
    (select id from categories where slug = 'i-calzoni'),
    'Tradizionale',
    'calzone-tradizionale',
    'pomodoro, mozzarella, prosciutto, funghi, ricotta',
    9.40,
    null,
    '["calzone"]',
    1,
    0,
    520
  ),
  (
    (select id from categories where slug = 'i-calzoni'),
    '4 Formaggi',
    'calzone-4-formaggi',
    'mozzarella, gorgonzola, scamorza affumicata, monte veronese dop',
    9.40,
    null,
    '["calzone"]',
    1,
    0,
    530
  ),
  (
    (select id from categories where slug = 'i-calzoni'),
    'Capri',
    'capri',
    'pomodoro, bufala campana dop, cipolla caramellata, pomodorini cirio, basilico',
    10.80,
    null,
    '["calzone"]',
    1,
    0,
    540
  ),
  (
    (select id from categories where slug = 'calzoni-in-fritteria'),
    'Caruseddu',
    'caruseddu',
    'pomodoro, mozzarella, origano',
    9.10,
    null,
    '["fritto"]',
    1,
    0,
    550
  ),
  (
    (select id from categories where slug = 'calzoni-in-fritteria'),
    'Tradizionale',
    'fritteria-tradizionale',
    'pomodoro, mozzarella, prosciutto, funghi',
    9.70,
    null,
    '["fritto"]',
    1,
    0,
    560
  ),
  (
    (select id from categories where slug = 'calzoni-in-fritteria'),
    'Veronese',
    'veronese',
    'pomodoro, mozzarella, scamorza affumicata, tastasal',
    9.70,
    null,
    '["fritto"]',
    1,
    0,
    570
  );

insert or ignore into menu_item_ingredients (menu_item_id, ingredient_id, is_removable, sort_order)
values
  ((select id from menu_items where slug = 'ale'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'ale'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'ale'), (select id from ingredients where slug = 'funghi-freschi'), 1, 30),
  ((select id from menu_items where slug = 'ale'), (select id from ingredients where slug = 'tastasal'), 1, 40),
  ((select id from menu_items where slug = 'ale'), (select id from ingredients where slug = 'monte-veronese-dop'), 1, 50),
  ((select id from menu_items where slug = 'andre'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'andre'), (select id from ingredients where slug = 'peperoni-grigliati'), 1, 20),
  ((select id from menu_items where slug = 'andre'), (select id from ingredients where slug = 'gorgonzola'), 1, 30),
  ((select id from menu_items where slug = 'andre'), (select id from ingredients where slug = 'nduja'), 1, 40),
  ((select id from menu_items where slug = 'baldo'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'baldo'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'baldo'), (select id from ingredients where slug = 'patate-cubettate-al-forno'), 1, 30),
  ((select id from menu_items where slug = 'baldo'), (select id from ingredients where slug = 'porcini'), 1, 40),
  ((select id from menu_items where slug = 'baldo'), (select id from ingredients where slug = 'wurstel'), 1, 50),
  ((select id from menu_items where slug = 'baldo'), (select id from ingredients where slug = 'scamorza-affumicata'), 1, 60),
  ((select id from menu_items where slug = 'boscalola'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'boscalola'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'boscalola'), (select id from ingredients where slug = 'porcini'), 1, 30),
  ((select id from menu_items where slug = 'boscalola'), (select id from ingredients where slug = 'grana'), 1, 40),
  ((select id from menu_items where slug = 'boscalola'), (select id from ingredients where slug = 'salamino-piccante'), 1, 50),
  ((select id from menu_items where slug = 'briosa'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'briosa'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'briosa'), (select id from ingredients where slug = 'pancetta-affumicata'), 1, 30),
  ((select id from menu_items where slug = 'briosa'), (select id from ingredients where slug = 'grana'), 1, 40),
  ((select id from menu_items where slug = 'briosa'), (select id from ingredients where slug = 'patate-cubettate-al-forno'), 1, 50),
  ((select id from menu_items where slug = 'briosa'), (select id from ingredients where slug = 'brie'), 1, 60),
  ((select id from menu_items where slug = 'bufalina'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'bufalina'), (select id from ingredients where slug = 'bufala-campana-dop'), 1, 20),
  ((select id from menu_items where slug = 'bufalina'), (select id from ingredients where slug = 'pomodorini-freschi'), 1, 30),
  ((select id from menu_items where slug = 'bufalina'), (select id from ingredients where slug = 'olive-nere'), 1, 40),
  ((select id from menu_items where slug = 'bufalina'), (select id from ingredients where slug = 'basilico'), 1, 50),
  ((select id from menu_items where slug = 'bufalina'), (select id from ingredients where slug = 'olio-extravergine'), 0, 60),
  ((select id from menu_items where slug = 'calabrese'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'calabrese'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'calabrese'), (select id from ingredients where slug = 'olive-nere'), 1, 30),
  ((select id from menu_items where slug = 'calabrese'), (select id from ingredients where slug = 'pecorino-reggino'), 1, 40),
  ((select id from menu_items where slug = 'calabrese'), (select id from ingredients where slug = 'nduja'), 1, 50),
  ((select id from menu_items where slug = 'campagnola'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'campagnola'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'campagnola'), (select id from ingredients where slug = 'prosciutto'), 1, 30),
  ((select id from menu_items where slug = 'campagnola'), (select id from ingredients where slug = 'pomodorini-cirio'), 1, 40),
  ((select id from menu_items where slug = 'campagnola'), (select id from ingredients where slug = 'olive-nere'), 1, 50),
  ((select id from menu_items where slug = 'campagnola'), (select id from ingredients where slug = 'scaglie-di-grana'), 1, 60),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'prosciutto'), 1, 30),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'funghi'), 1, 40),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'carciofi'), 1, 50),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'olive-nere'), 1, 60),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'capperi'), 1, 70),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'acciughe'), 1, 80),
  ((select id from menu_items where slug = 'capricciosa'), (select id from ingredients where slug = 'origano-siciliano'), 1, 90),
  ((select id from menu_items where slug = 'caretera'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'caretera'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'caretera'), (select id from ingredients where slug = 'radicchio'), 1, 30),
  ((select id from menu_items where slug = 'caretera'), (select id from ingredients where slug = 'gorgonzola'), 1, 40),
  ((select id from menu_items where slug = 'caretera'), (select id from ingredients where slug = 'tastasal'), 1, 50),
  ((select id from menu_items where slug = 'caretera'), (select id from ingredients where slug = 'speck-alto-adige-igp'), 1, 60),
  ((select id from menu_items where slug = 'deliziosa'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'deliziosa'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'deliziosa'), (select id from ingredients where slug = 'zucchine-grigliate'), 1, 30),
  ((select id from menu_items where slug = 'deliziosa'), (select id from ingredients where slug = 'pomodorini-cirio'), 1, 40),
  ((select id from menu_items where slug = 'deliziosa'), (select id from ingredients where slug = 'philadelphia'), 1, 50),
  ((select id from menu_items where slug = 'estate'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'estate'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'estate'), (select id from ingredients where slug = 'pomodorini-cirio'), 1, 30),
  ((select id from menu_items where slug = 'estate'), (select id from ingredients where slug = 'scaglie-di-grana'), 1, 40),
  ((select id from menu_items where slug = 'estate'), (select id from ingredients where slug = 'basilico'), 1, 50),
  ((select id from menu_items where slug = 'filanda'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'filanda'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'filanda'), (select id from ingredients where slug = 'radicchio'), 1, 30),
  ((select id from menu_items where slug = 'filanda'), (select id from ingredients where slug = 'philadelphia'), 1, 40),
  ((select id from menu_items where slug = 'filanda'), (select id from ingredients where slug = 'scaglie-di-grana'), 1, 50),
  ((select id from menu_items where slug = 'golosa'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'golosa'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'golosa'), (select id from ingredients where slug = 'porcini'), 1, 30),
  ((select id from menu_items where slug = 'golosa'), (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 1, 40),
  ((select id from menu_items where slug = 'golosa'), (select id from ingredients where slug = 'gorgonzola'), 1, 50),
  ((select id from menu_items where slug = 'incontri'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'incontri'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'incontri'), (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 1, 30),
  ((select id from menu_items where slug = 'incontri'), (select id from ingredients where slug = 'stracciatella'), 1, 40),
  ((select id from menu_items where slug = 'incontri'), (select id from ingredients where slug = 'pesto-homemade'), 1, 50),
  ((select id from menu_items where slug = 'inferno'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'inferno'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'inferno'), (select id from ingredients where slug = 'nduja'), 1, 30),
  ((select id from menu_items where slug = 'inferno'), (select id from ingredients where slug = 'salamino-piccante'), 1, 40),
  ((select id from menu_items where slug = 'inferno'), (select id from ingredients where slug = 'peperoncino'), 1, 50),
  ((select id from menu_items where slug = 'margherita'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'margherita'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'margherita-2-0'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'margherita-2-0'), (select id from ingredients where slug = 'bufala-campana-dop-bio'), 1, 20),
  ((select id from menu_items where slug = 'margherita-2-0'), (select id from ingredients where slug = 'pomodorino-confit'), 1, 30),
  ((select id from menu_items where slug = 'margherita-2-0'), (select id from ingredients where slug = 'basilico'), 1, 40),
  ((select id from menu_items where slug = 'marinara'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'marinara'), (select id from ingredients where slug = 'olio-allaglio'), 0, 20),
  ((select id from menu_items where slug = 'marinara'), (select id from ingredients where slug = 'origano-siciliano'), 1, 30),
  ((select id from menu_items where slug = 'paradiso'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'paradiso'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'paradiso'), (select id from ingredients where slug = 'funghi-freschi'), 1, 30),
  ((select id from menu_items where slug = 'paradiso'), (select id from ingredients where slug = 'ricotta'), 1, 40),
  ((select id from menu_items where slug = 'paradiso'), (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 1, 50),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'pomodorini-secchi'), 1, 30),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'tonno'), 1, 40),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'bufala-campana-dop'), 1, 50),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'cipolla'), 1, 60),
  ((select id from menu_items where slug = 'partenopea'), (select id from ingredients where slug = 'basilico'), 1, 70),
  ((select id from menu_items where slug = 'parmigiana-crunch'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'parmigiana-crunch'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'parmigiana-crunch'), (select id from ingredients where slug = 'straccetti-di-melanzana-fritta'), 1, 30),
  ((select id from menu_items where slug = 'parmigiana-crunch'), (select id from ingredients where slug = 'grana'), 1, 40),
  ((select id from menu_items where slug = 'patatine-fritte'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'patatine-fritte'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'patatine-fritte'), (select id from ingredients where slug = 'patatine-fritte'), 1, 30),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'salamino-piccante'), 1, 30),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'olive-nere'), 1, 40),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'prosciutto'), 1, 50),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'funghi'), 1, 60),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'peperoni-grigliati'), 1, 70),
  ((select id from menu_items where slug = 'pizza-della-casa'), (select id from ingredients where slug = 'wurstel'), 1, 80),
  ((select id from menu_items where slug = 'pizza-scegli-tu'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'pizza-scegli-tu'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'prosciutto-e-funghi'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'prosciutto-e-funghi'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'prosciutto-e-funghi'), (select id from ingredients where slug = 'funghi'), 1, 30),
  ((select id from menu_items where slug = 'prosciutto-e-funghi'), (select id from ingredients where slug = 'prosciutto'), 1, 40),
  ((select id from menu_items where slug = 'pugliese'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'pugliese'), (select id from ingredients where slug = 'salamino-piccante'), 1, 20),
  ((select id from menu_items where slug = 'pugliese'), (select id from ingredients where slug = 'olive-nere'), 1, 30),
  ((select id from menu_items where slug = 'pugliese'), (select id from ingredients where slug = 'scamorza-affumicata'), 1, 40),
  ((select id from menu_items where slug = '4-formaggi'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = '4-formaggi'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = '4-formaggi'), (select id from ingredients where slug = 'scamorza-affumicata'), 1, 30),
  ((select id from menu_items where slug = '4-formaggi'), (select id from ingredients where slug = 'emmenthal'), 1, 40),
  ((select id from menu_items where slug = '4-formaggi'), (select id from ingredients where slug = 'ricotta'), 1, 50),
  ((select id from menu_items where slug = '4-formaggi'), (select id from ingredients where slug = 'gorgonzola'), 1, 60),
  ((select id from menu_items where slug = '4-stagioni'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = '4-stagioni'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = '4-stagioni'), (select id from ingredients where slug = 'prosciutto'), 1, 30),
  ((select id from menu_items where slug = '4-stagioni'), (select id from ingredients where slug = 'funghi'), 1, 40),
  ((select id from menu_items where slug = '4-stagioni'), (select id from ingredients where slug = 'carciofi'), 1, 50),
  ((select id from menu_items where slug = '4-stagioni'), (select id from ingredients where slug = 'olive-nere'), 1, 60),
  ((select id from menu_items where slug = 'rione'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'rione'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'rione'), (select id from ingredients where slug = 'funghi'), 1, 30),
  ((select id from menu_items where slug = 'rione'), (select id from ingredients where slug = 'scamorza-affumicata'), 1, 40),
  ((select id from menu_items where slug = 'rione'), (select id from ingredients where slug = 'grana'), 1, 50),
  ((select id from menu_items where slug = 'rione'), (select id from ingredients where slug = 'speck-alto-adige-igp'), 1, 60),
  ((select id from menu_items where slug = 'romanaccia'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'romanaccia'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'romanaccia'), (select id from ingredients where slug = 'guanciale-affumicato'), 1, 30),
  ((select id from menu_items where slug = 'romanaccia'), (select id from ingredients where slug = 'crema-carbonara'), 1, 40),
  ((select id from menu_items where slug = 'rustichella'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'rustichella'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'rustichella'), (select id from ingredients where slug = 'stracchino'), 1, 30),
  ((select id from menu_items where slug = 'rustichella'), (select id from ingredients where slug = 'porcini'), 1, 40),
  ((select id from menu_items where slug = 'rustichella'), (select id from ingredients where slug = 'grana'), 1, 50),
  ((select id from menu_items where slug = 'rustichella'), (select id from ingredients where slug = 'speck-alto-adige-igp'), 1, 60),
  ((select id from menu_items where slug = 'sotto-bosco'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'sotto-bosco'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'sotto-bosco'), (select id from ingredients where slug = 'cipolla-caramellata'), 1, 30),
  ((select id from menu_items where slug = 'sotto-bosco'), (select id from ingredients where slug = 'misto-bosco'), 1, 40),
  ((select id from menu_items where slug = 'sotto-bosco'), (select id from ingredients where slug = 'soppressa-dolce-della-lessinia'), 1, 50),
  ((select id from menu_items where slug = 'sfiziosa'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'sfiziosa'), (select id from ingredients where slug = 'melanzane-grigliate'), 1, 20),
  ((select id from menu_items where slug = 'sfiziosa'), (select id from ingredients where slug = 'bufala-campana-dop'), 1, 30),
  ((select id from menu_items where slug = 'sfiziosa'), (select id from ingredients where slug = 'olive-nere'), 1, 40),
  ((select id from menu_items where slug = 'sfiziosa'), (select id from ingredients where slug = 'pomodorini-cirio'), 1, 50),
  ((select id from menu_items where slug = 'siciliana'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'siciliana'), (select id from ingredients where slug = 'salamino-piccante'), 1, 20),
  ((select id from menu_items where slug = 'siciliana'), (select id from ingredients where slug = 'olive-nere'), 1, 30),
  ((select id from menu_items where slug = 'siciliana'), (select id from ingredients where slug = 'acciughe'), 1, 40),
  ((select id from menu_items where slug = 'siciliana'), (select id from ingredients where slug = 'capperi'), 1, 50),
  ((select id from menu_items where slug = 'siciliana'), (select id from ingredients where slug = 'origano-siciliano'), 1, 60),
  ((select id from menu_items where slug = 'tonno-e-cipolla'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'tonno-e-cipolla'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'tonno-e-cipolla'), (select id from ingredients where slug = 'tonno'), 1, 30),
  ((select id from menu_items where slug = 'tonno-e-cipolla'), (select id from ingredients where slug = 'cipolla'), 1, 40),
  ((select id from menu_items where slug = 'vegetariana'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'vegetariana'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'vegetariana'), (select id from ingredients where slug = 'verdure-di-stagione'), 1, 30),
  ((select id from menu_items where slug = 'vulcano'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'vulcano'), (select id from ingredients where slug = 'guanciale-affumicato'), 1, 20),
  ((select id from menu_items where slug = 'vulcano'), (select id from ingredients where slug = 'patate-cubettate-al-forno'), 1, 30),
  ((select id from menu_items where slug = 'vulcano'), (select id from ingredients where slug = 'friarielli-passati-in-padella-con-aglio'), 1, 40),
  ((select id from menu_items where slug = 'vulcano'), (select id from ingredients where slug = 'burrata'), 1, 50),
  ((select id from menu_items where slug = 'vulcano'), (select id from ingredients where slug = 'fili-di-peperoncino'), 1, 60),
  ((select id from menu_items where slug = 'matteo'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'matteo'), (select id from ingredients where slug = 'gorgonzola'), 1, 20),
  ((select id from menu_items where slug = 'matteo'), (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 1, 30),
  ((select id from menu_items where slug = 'matteo'), (select id from ingredients where slug = 'rucola'), 1, 40),
  ((select id from menu_items where slug = 'matteo'), (select id from ingredients where slug = 'funghi-freschi'), 1, 50),
  ((select id from menu_items where slug = 'matteo'), (select id from ingredients where slug = 'noci'), 1, 60),
  ((select id from menu_items where slug = 'mik'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'mik'), (select id from ingredients where slug = 'spinaci'), 1, 20),
  ((select id from menu_items where slug = 'mik'), (select id from ingredients where slug = 'ricotta'), 1, 30),
  ((select id from menu_items where slug = 'mik'), (select id from ingredients where slug = 'salamino-piccante'), 1, 40),
  ((select id from menu_items where slug = 'mik'), (select id from ingredients where slug = 'carciofi'), 1, 50),
  ((select id from menu_items where slug = 'peperina'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'peperina'), (select id from ingredients where slug = 'zucchine-grigliate'), 1, 20),
  ((select id from menu_items where slug = 'peperina'), (select id from ingredients where slug = 'pancetta-arrotolata-piccante'), 1, 30),
  ((select id from menu_items where slug = 'peperina'), (select id from ingredients where slug = 'stracciatella'), 1, 40),
  ((select id from menu_items where slug = 'peperina'), (select id from ingredients where slug = 'peperoncini-in-fili-sottili'), 1, 50),
  ((select id from menu_items where slug = 'sapore-d-amarone'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'sapore-d-amarone'), (select id from ingredients where slug = 'gelatina-di-amarone-docg'), 1, 20),
  ((select id from menu_items where slug = 'sapore-d-amarone'), (select id from ingredients where slug = 'coppa-affinata-in-amarone-docg'), 1, 30),
  ((select id from menu_items where slug = 'sapore-d-amarone'), (select id from ingredients where slug = 'radicchio'), 1, 40),
  ((select id from menu_items where slug = 'sapore-d-amarone'), (select id from ingredients where slug = 'anelli-di-porro'), 1, 50),
  ((select id from menu_items where slug = 'stanca-bianca'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'stanca-bianca'), (select id from ingredients where slug = 'stracchino'), 1, 20),
  ((select id from menu_items where slug = 'stanca-bianca'), (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 1, 30),
  ((select id from menu_items where slug = 'stanca-bianca'), (select id from ingredients where slug = 'porcini'), 1, 40),
  ((select id from menu_items where slug = 'trionfo'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'trionfo'), (select id from ingredients where slug = 'funghi-freschi'), 1, 20),
  ((select id from menu_items where slug = 'trionfo'), (select id from ingredients where slug = 'pomodorini-cirio'), 1, 30),
  ((select id from menu_items where slug = 'trionfo'), (select id from ingredients where slug = 'rucola'), 1, 40),
  ((select id from menu_items where slug = 'trionfo'), (select id from ingredients where slug = 'burrata'), 1, 50),
  ((select id from menu_items where slug = 'tatanka'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'tatanka'), (select id from ingredients where slug = 'patate-cubettate-al-forno'), 1, 20),
  ((select id from menu_items where slug = 'tatanka'), (select id from ingredients where slug = 'brie'), 1, 30),
  ((select id from menu_items where slug = 'tatanka'), (select id from ingredients where slug = 'rosmarino'), 1, 40),
  ((select id from menu_items where slug = 'tatanka'), (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'), 1, 50),
  ((select id from menu_items where slug = 'amatriciana'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'amatriciana'), (select id from ingredients where slug = 'pancetta-affumicata'), 1, 20),
  ((select id from menu_items where slug = 'amatriciana'), (select id from ingredients where slug = 'misto-bosco'), 1, 30),
  ((select id from menu_items where slug = 'amatriciana'), (select id from ingredients where slug = 'pepe'), 1, 40),
  ((select id from menu_items where slug = 'amatriciana'), (select id from ingredients where slug = 'caciocavallo-della-piana'), 1, 50),
  ((select id from menu_items where slug = 'polpo-intanato'), (select id from ingredients where slug = 'doppia-salsa-di-pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'polpo-intanato'), (select id from ingredients where slug = 'tentacoli-di-polpo'), 1, 20),
  ((select id from menu_items where slug = 'polpo-intanato'), (select id from ingredients where slug = 'olive-nere'), 1, 30),
  ((select id from menu_items where slug = 'polpo-intanato'), (select id from ingredients where slug = 'basilico'), 1, 40),
  ((select id from menu_items where slug = 'frutti-di-mare'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'frutti-di-mare'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'frutti-di-mare'), (select id from ingredients where slug = 'cozze-e-frutti-di-mare'), 1, 30),
  ((select id from menu_items where slug = 'frutti-di-mare'), (select id from ingredients where slug = 'prezzemolo'), 1, 40),
  ((select id from menu_items where slug = 'new-york-ale'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'new-york-ale'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'new-york-ale'), (select id from ingredients where slug = 'burrata'), 1, 30),
  ((select id from menu_items where slug = 'new-york-ale'), (select id from ingredients where slug = 'mortadella-bologna-dop'), 1, 40),
  ((select id from menu_items where slug = 'new-york-ale'), (select id from ingredients where slug = 'crema-al-pistacchio'), 1, 50),
  ((select id from menu_items where slug = 'new-york-ale'), (select id from ingredients where slug = 'pomodorini-freschi'), 1, 60),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'gamberetti'), 1, 30),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'zucchine-grigliate'), 1, 40),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'philadelphia'), 1, 50),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'pinoli'), 1, 60),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'burrata'), 1, 70),
  ((select id from menu_items where slug = 'madame'), (select id from ingredients where slug = 'basilico'), 1, 80),
  ((select id from menu_items where slug = 'toscanaccia'), (select id from ingredients where slug = 'schiacciata'), 0, 10),
  ((select id from menu_items where slug = 'toscanaccia'), (select id from ingredients where slug = 'lombo-stagionato-al-pepe-rosa'), 1, 20),
  ((select id from menu_items where slug = 'toscanaccia'), (select id from ingredients where slug = 'grana'), 1, 30),
  ((select id from menu_items where slug = 'toscanaccia'), (select id from ingredients where slug = 'carciofo-alla-griglia'), 1, 40),
  ((select id from menu_items where slug = 'toscanaccia'), (select id from ingredients where slug = 'olio-extravergine-chianti-dop'), 0, 50),
  ((select id from menu_items where slug = 'calzone-tradizionale'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'calzone-tradizionale'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'calzone-tradizionale'), (select id from ingredients where slug = 'prosciutto'), 1, 30),
  ((select id from menu_items where slug = 'calzone-tradizionale'), (select id from ingredients where slug = 'funghi'), 1, 40),
  ((select id from menu_items where slug = 'calzone-tradizionale'), (select id from ingredients where slug = 'ricotta'), 1, 50),
  ((select id from menu_items where slug = 'calzone-4-formaggi'), (select id from ingredients where slug = 'mozzarella'), 1, 10),
  ((select id from menu_items where slug = 'calzone-4-formaggi'), (select id from ingredients where slug = 'gorgonzola'), 1, 20),
  ((select id from menu_items where slug = 'calzone-4-formaggi'), (select id from ingredients where slug = 'scamorza-affumicata'), 1, 30),
  ((select id from menu_items where slug = 'calzone-4-formaggi'), (select id from ingredients where slug = 'monte-veronese-dop'), 1, 40),
  ((select id from menu_items where slug = 'capri'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'capri'), (select id from ingredients where slug = 'bufala-campana-dop'), 1, 20),
  ((select id from menu_items where slug = 'capri'), (select id from ingredients where slug = 'cipolla-caramellata'), 1, 30),
  ((select id from menu_items where slug = 'capri'), (select id from ingredients where slug = 'pomodorini-cirio'), 1, 40),
  ((select id from menu_items where slug = 'capri'), (select id from ingredients where slug = 'basilico'), 1, 50),
  ((select id from menu_items where slug = 'caruseddu'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'caruseddu'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'caruseddu'), (select id from ingredients where slug = 'origano'), 1, 30),
  ((select id from menu_items where slug = 'fritteria-tradizionale'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'fritteria-tradizionale'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'fritteria-tradizionale'), (select id from ingredients where slug = 'prosciutto'), 1, 30),
  ((select id from menu_items where slug = 'fritteria-tradizionale'), (select id from ingredients where slug = 'funghi'), 1, 40),
  ((select id from menu_items where slug = 'veronese'), (select id from ingredients where slug = 'pomodoro'), 0, 10),
  ((select id from menu_items where slug = 'veronese'), (select id from ingredients where slug = 'mozzarella'), 1, 20),
  ((select id from menu_items where slug = 'veronese'), (select id from ingredients where slug = 'scamorza-affumicata'), 1, 30),
  ((select id from menu_items where slug = 'veronese'), (select id from ingredients where slug = 'tastasal'), 1, 40);

insert or ignore into menu_item_allowed_extras (menu_item_id, extra_ingredient_id)
select menu_items.id, extra_ingredients.id
from menu_items
inner join categories on categories.id = menu_items.category_id
inner join extra_ingredients on extra_ingredients.ingredient_id in (
  (select id from ingredients where slug = 'mozzarella'),
  (select id from ingredients where slug = 'bufala-campana-dop'),
  (select id from ingredients where slug = 'burrata'),
  (select id from ingredients where slug = 'stracciatella'),
  (select id from ingredients where slug = 'gorgonzola'),
  (select id from ingredients where slug = 'nduja'),
  (select id from ingredients where slug = 'salamino-piccante'),
  (select id from ingredients where slug = 'olive-nere'),
  (select id from ingredients where slug = 'funghi-freschi'),
  (select id from ingredients where slug = 'porcini'),
  (select id from ingredients where slug = 'prosciutto'),
  (select id from ingredients where slug = 'crudo-di-parma-dop-24-30-mesi'),
  (select id from ingredients where slug = 'scamorza-affumicata'),
  (select id from ingredients where slug = 'grana'),
  (select id from ingredients where slug = 'peperoni-grigliati'),
  (select id from ingredients where slug = 'cipolla'),
  (select id from ingredients where slug = 'tonno'),
  (select id from ingredients where slug = 'patate-cubettate-al-forno'),
  (select id from ingredients where slug = 'philadelphia'),
  (select id from ingredients where slug = 'basilico')
)
where categories.slug in ('le-pizze', 'le-bianche', 'le-speciali', 'i-calzoni', 'calzoni-in-fritteria');

insert or ignore into product_options (
  menu_item_id,
  option_group_name,
  option_group_slug,
  option_name,
  price_delta,
  is_default,
  sort_order,
  active
)
select menu_items.id, values_table.option_group_name, values_table.option_group_slug, values_table.option_name, values_table.price_delta, values_table.is_default, values_table.sort_order, 1
from menu_items
inner join categories on categories.id = menu_items.category_id
cross join (
  select 'Impasto' as option_group_name, 'impasto' as option_group_slug, 'Classico' as option_name, 0.00 as price_delta, 1 as is_default, 10 as sort_order
  union all select 'Impasto', 'impasto', 'Integrale', 1.50, 0, 20
  union all select 'Impasto', 'impasto', 'Senza glutine', 2.50, 0, 30
) as values_table
where categories.slug in ('le-pizze', 'le-bianche', 'le-speciali', 'i-calzoni');
